# Generated by Django 4.2.1 on 2023-05-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[('DAY', 'раз в день'), ('WEEK', 'раз в неделю'), ('MONTH', 'раз в месяц')], max_length=100, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('FINISH', 'завершена'), ('CREATE', 'создана'), ('START', 'запущена')], max_length=100, verbose_name='Статус')),
                ('client', models.ManyToManyField(to='mailing.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('header',),
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('status', models.CharField(choices=[('Success', 'успешно'), ('Failure', 'отказ')], max_length=100, verbose_name='Статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailing', verbose_name='Рассылка')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'лог отправки письма',
                'verbose_name_plural': 'логи отправок писем',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ManyToManyField(to='mailing.message', verbose_name='Сообщение'),
        ),
    ]
