# Generated by Django 4.2.1 on 2023-06-26 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0002_remove_mailing_client_remove_mailinglogs_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mailinglogs',
            name='message',
        ),
        migrations.RemoveField(
            model_name='mailinglogs',
            name='user',
        ),
        migrations.AddField(
            model_name='mailing',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='finish_date',
            field=models.DateField(default='2024-01-01', verbose_name='Дата завершения рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='finish_time',
            field=models.TimeField(default='00:00', verbose_name='Время завершения рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время рассылки'),
        ),
        migrations.RemoveField(
            model_name='mailinglogs',
            name='mailing',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Фамилия Имя Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='mailing.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='mailing',
            field=models.ManyToManyField(blank=True, null=True, to='mailing.mailing', verbose_name='Рассылка'),
        ),
    ]
