# Generated by Django 4.2.1 on 2023-06-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_mailing_is_active_remove_mailinglogs_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglogs',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailing', verbose_name='Рассылка'),
        ),
    ]
